// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_app.tsx";
import * as $$0 from "./islands/ActiveLink.tsx";
import * as $$1 from "./islands/Animate.tsx";
import * as $$2 from "./islands/CurrentPage.tsx";
import * as $$3 from "./islands/HeaderBg.tsx";
import * as $$4 from "./islands/Marquee.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
  },
  islands: {
    "./islands/ActiveLink.tsx": $$0,
    "./islands/Animate.tsx": $$1,
    "./islands/CurrentPage.tsx": $$2,
    "./islands/HeaderBg.tsx": $$3,
    "./islands/Marquee.tsx": $$4,
  },
  baseUrl: import.meta.url,
};

export default manifest;
