// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$0 from "./sections/Hero.tsx";
import * as $$$$$$1 from "./sections/Theme.tsx";
import * as $$$$$$2 from "./sections/Footer.tsx";
import * as $$$$$$3 from "./sections/Portfolio/Projects.tsx";
import * as $$$$$$4 from "./sections/Portfolio/ProjectHeader.tsx";
import * as $$$$$$5 from "./sections/Portfolio/Hero.tsx";
import * as $$$$$$6 from "./sections/Portfolio/AboutContent.tsx";
import * as $$$$$$7 from "./sections/Portfolio/Spacer.tsx";
import * as $$$$$$8 from "./sections/Portfolio/PhotoGroup.tsx";
import * as $$$$$$9 from "./sections/Portfolio/ProjectHighlight.tsx";
import * as $$$$$$10 from "./sections/Portfolio/DarkContent.tsx";
import * as $$$$$$11 from "./sections/Portfolio/ColorBar.tsx";
import * as $$$$$$12 from "./sections/Portfolio/ProjectInfo.tsx";
import * as $$$$$$13 from "./sections/Portfolio/Footer.tsx";
import * as $$$$$$14 from "./sections/Portfolio/Head.tsx";
import * as $$$$$$15 from "./sections/Portfolio/Header.tsx";
import * as $$$$$$16 from "./sections/Portfolio/ProjectNav.tsx";
import * as $$$$$$17 from "./sections/SimpleTextList.tsx";
import * as $$$$$$18 from "./sections/ParagraphList.tsx";
import * as $$$$$$$$$$$0 from "./apps/decohub.ts";
import * as $$$$$$$$$$$1 from "./apps/site.ts";

const manifest = {
  "sections": {
    "deco-sites/carol-calca/sections/Footer.tsx": $$$$$$2,
    "deco-sites/carol-calca/sections/Hero.tsx": $$$$$$0,
    "deco-sites/carol-calca/sections/ParagraphList.tsx": $$$$$$18,
    "deco-sites/carol-calca/sections/Portfolio/AboutContent.tsx": $$$$$$6,
    "deco-sites/carol-calca/sections/Portfolio/ColorBar.tsx": $$$$$$11,
    "deco-sites/carol-calca/sections/Portfolio/DarkContent.tsx": $$$$$$10,
    "deco-sites/carol-calca/sections/Portfolio/Footer.tsx": $$$$$$13,
    "deco-sites/carol-calca/sections/Portfolio/Head.tsx": $$$$$$14,
    "deco-sites/carol-calca/sections/Portfolio/Header.tsx": $$$$$$15,
    "deco-sites/carol-calca/sections/Portfolio/Hero.tsx": $$$$$$5,
    "deco-sites/carol-calca/sections/Portfolio/PhotoGroup.tsx": $$$$$$8,
    "deco-sites/carol-calca/sections/Portfolio/ProjectHeader.tsx": $$$$$$4,
    "deco-sites/carol-calca/sections/Portfolio/ProjectHighlight.tsx": $$$$$$9,
    "deco-sites/carol-calca/sections/Portfolio/ProjectInfo.tsx": $$$$$$12,
    "deco-sites/carol-calca/sections/Portfolio/ProjectNav.tsx": $$$$$$16,
    "deco-sites/carol-calca/sections/Portfolio/Projects.tsx": $$$$$$3,
    "deco-sites/carol-calca/sections/Portfolio/Spacer.tsx": $$$$$$7,
    "deco-sites/carol-calca/sections/SimpleTextList.tsx": $$$$$$17,
    "deco-sites/carol-calca/sections/Theme.tsx": $$$$$$1,
  },
  "apps": {
    "deco-sites/carol-calca/apps/decohub.ts": $$$$$$$$$$$0,
    "deco-sites/carol-calca/apps/site.ts": $$$$$$$$$$$1,
  },
  "name": "deco-sites/carol-calca",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
